import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="h-[80px]">
          <Header />
        </div>
        <div className="min-h-[calc(100vh-80px)]">{children}</div>
        <div className="bg-[#035635]">
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
